import React, { useEffect } from "react";
import "../CSS/faq.css";

function FAQ() {
    useEffect(() => {
        // Smooth scrolling for anchor links
        const anchors = document.querySelectorAll('a[href^="#"]');
        const handleAnchorClick = function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({ behavior: 'smooth' });
            }
        };
        anchors.forEach(anchor => {
            anchor.addEventListener('click', handleAnchorClick);
        });

        // Toggle FAQ answer visibility
        const faqItems = document.querySelectorAll('.faq-item');
        const handleToggle = (e) => {
            e.currentTarget.classList.toggle('active');
        };
        faqItems.forEach(item => {
            item.addEventListener('click', handleToggle);
        });

        // Scroll-trigger animation using IntersectionObserver
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('animate');
                }
            });
        }, { threshold: 0.3 });

        faqItems.forEach(item => observer.observe(item));

        // Cleanup
        return () => {
            anchors.forEach(anchor => {
                anchor.removeEventListener('click', handleAnchorClick);
            });
            faqItems.forEach(item => {
                item.removeEventListener('click', handleToggle);
            });
            observer.disconnect();
        };
    }, []);

    return (
        <section id="faq">
            <div className="faq">
                <h2>Frequently Asked Questions (FAQ's)</h2>
                <div className="faq2">
                    <div className="faq-container">
                        {[
                            {
                                q: "What is QReatify?",
                                a: "QReatify is a simple tool that converts URLs into QR codes, making it easier to share links quickly and efficiently."
                            },
                            {
                                q: "How do I use QReatify?",
                                a: "Enter the URL you want to convert into the input field, click \"Generate QR Code,\" and instantly get your QR code."
                            },
                            {
                                q: "Is QReatify free to use?",
                                a: "Yes, QReatify is completely free and available for everyone."
                            },
                            {
                                q: "Can I customize the generated QR code?",
                                a: "Yes, QReatify uses the qr-code-styling library, which allows you to customize your QR code with different colors, embedded logos, and styling options to match your brand or preferences."
                            },
                            {
                                q: "Do I need an account to use QReatify?",
                                a: "No account is required! QReatify is designed for quick and hassle-free usage."
                            },
                            {
                                q: "Are the generated QR codes permanent?",
                                a: "Yes, the QR codes you create with QReatify are static and will work as long as the URL remains valid."
                            },
                            {
                                q: "Can I scan the QR codes with any device?",
                                a: "Yes, the QR codes generated by QReatify can be scanned with any QR code scanner app or device camera."
                            }
                        ].map((faq, index) => (
                            <div className="faq-item" key={index}>
                                <div className="faq-question">{faq.q}</div>
                                <div className="faq-answer">{faq.a}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>
    );
}

export default FAQ;
