import React, { useEffect } from "react";
import "../CSS/faq.css";

function FAQ() {
    useEffect(() => {

        const anchors = document.querySelectorAll('a[href^="#"]');
        anchors.forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth' });
                }
            });
        });


        const faqItems = document.querySelectorAll('.faq-item');
        faqItems.forEach(item => {
            item.addEventListener('click', () => {
                item.classList.toggle('active');
            });
        });


        return () => {
            anchors.forEach(anchor => {
                anchor.removeEventListener('click', () => { });
            });
            faqItems.forEach(item => {
                item.removeEventListener('click', () => { });
            });
        };
    }, []);

    return (
        <section id="faq">
            <div className="faq">
                <h2>Frequently Asked Questions (FAQ's)</h2>
                <div className="faq2">
                    <div className="faq-container">
                        <div className="faq-item">
                            <div className="faq-question">What is QReatify?</div>
                            <div className="faq-answer">
                                QReatify is a simple tool that converts URLs into QR codes, making it easier to share links quickly and efficiently.
                            </div>
                        </div>
                        <div className="faq-item">
                            <div className="faq-question">How do I use QReatify?</div>
                            <div className="faq-answer">
                                Enter the URL you want to convert into the input field, click "Generate QR Code," and instantly get your QR code.
                            </div>
                        </div>
                        <div className="faq-item">
                            <div className="faq-question">Is QReatify free to use?</div>
                            <div className="faq-answer">
                                Yes, QReatify is completely free and available for everyone.
                            </div>
                        </div>
                        <div className="faq-item">
                            <div className="faq-question">Can I customize the generated QR code?</div>
                            <div className="faq-answer">
                                Yes, QReatify uses the <code>qr-code-styling</code> library, which allows you to customize your QR code with different colors, embedded logos, and styling options to match your brand or preferences.                            </div>
                        </div>
                        <div className="faq-item">
                            <div className="faq-question">Do I need an account to use QReatify?</div>
                            <div className="faq-answer">
                                No account is required! QReatify is designed for quick and hassle-free usage.
                            </div>
                        </div>
                        <div className="faq-item">
                            <div className="faq-question">Are the generated QR codes permanent?</div>
                            <div className="faq-answer">
                                Yes, the QR codes you create with QReatify are static and will work as long as the URL remains valid.
                            </div>
                        </div>
                        <div className="faq-item">
                            <div className="faq-question">Can I scan the QR codes with any device?</div>
                            <div className="faq-answer">
                                Yes, the QR codes generated by QReatify can be scanned with any QR code scanner app or device camera.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}

export default FAQ;
